### ISSUE TITLE
Some functionality feedbacks

### ISSUE THREAD

**Issue by iokinpardo** [sintacs/sintacs-mwai-frontend-chatbot-settings#4] opened 2024-05-25 13:47 UTC
Hi team,

as we consider this pluging-addon with high value if you agree we can share several feedbacks we are facing in order to improve the full performance.

1. The parameters are saved correct internally (admin side) - both order and visibility. However when the form is showed in the front nothing is being saved into the specific chatbot through "Save to original" and "Reset to original" buttons. Just "Save" one seems to save fields values but nothing on the AIEngine backend.

2. I don't have very clear idea about what each button should be doing: "Save to original" and "Reset to original". Can you please detail those please? Any differences?

3. What means blue color bullets? See image below

4. Can the Temperature slider move from 0 to 1? Now 0.1 seems to be the lowest value.

Many thanks. 

![image](https://github.com/sintacs/sintacs-mwai-frontend-chatbot-settings/assets/6673107/9f8d1f7c-81cf-4352-8a29-1f98deb30e94)

**Comment by sintacs** [comment] 2024-05-25 15:57
Your feedback is highly appreciated, thank you. 

1. and 2. 
- The chatbot settings will be saved for each user and take only effect for the current user.
- Use the 'Save to Original' Button to save the user settings to the original chatbot, so that it will effect every user of this chatbot.
- Use the 'Reset to Original' Button to load the original chatbot settings into the form. Needs save to take effect for the current user.

3. - **The blue icon**: Indicates that the setting differs from the original.
4. The minium value is now 0.

I hope this answers you questions.

**Comment by iokinpardo** [comment] 2024-05-25 16:11
Thanks for the quick response.👌
It has complete sense what you have shared.

However it seems that when I click on Reset from Original, form fields are not being updated with the AIEngine chatbot information.

In the front form:

Save button runs fine for my user. (Current user). I can retrieve saved information correctly.

Save to Original: Does not save into AIEngine chatbot. I can not see the information saved on AIEngine admin side. Is this correct or I missed something?

Reset from Original: Have not been able to retrieve anything I have under AIEngine admin side for the specific chatbot.

Great the blue label and slider starting by 0. 👍

Regards.


Enviado desde mi Galaxy



-------- Mensaje original --------
De: sintacs ***@***.***>
Fecha: 25/5/24 17:57 (GMT+01:00)
Para: sintacs/sintacs-mwai-frontend-chatbot-settings ***@***.***>
Cc: iokinpardo ***@***.***>, Author ***@***.***>
Asunto: Re: [sintacs/sintacs-mwai-frontend-chatbot-settings] Some functionality feedbacks (Issue #4)


Your feedback is highly appreciated, thank you.

  1.  and 2.

  *   The chatbot settings will be saved for each user and take only effect for the current user.
  *   Use the 'Save to Original' Button to save the user settings to the original chatbot, so that it will effect every user of this chatbot.
  *   Use the 'Reset to Original' Button to load the original chatbot settings into the form. Needs save to take effect for the current user.

  1.
     *   The blue icon: Indicates that the setting differs from the original.
  2.  The minium value is now 0.

I hope this answers you questions.

**Comment by iokinpardo** [comment] 2024-05-25 16:30
I think I have found a possible reason. In order to Save to Original and Rest from Original, the shortcode requires the chatbot ID to be present, otherwise it does not work.

**Comment by iokinpardo** [comment] 2024-05-25 16:36
I have also noticed that at least for the "First sentence" field the ' char seems to be saved as \' each time so after couple of saving I'm getting "Let\\\\\'s begin...." for below sentence. Not sure if this happens on rest of fields.

"Let's begin and please go ahead with your first question."

**Comment by iokinpardo** [comment] 2024-05-25 18:27
I have noticed that those 3 important fields are not being saved. Rest run perfectly:

- Chatbot Name (empty is saved)
- Chatbot Environment (default is saved)
- Chatbot Model (default is saved)

**Comment by sintacs** [comment] 2024-05-26 08:47
Thank you for testing.

I just pushed some changes. The bugs you noticed should be fixed, I recommend uninstalling and reinstalling the plugin to avoid issues.

> I have also noticed that at least for the "First sentence" field the ' char seems to be saved as ' each time so after couple of saving I'm getting "Let\\'s begin...." for below sentence. Not sure if this happens on rest of fields.

I could not reproduce this but I made some changes that might prevent it. Please test it.

**Closed** 2024-05-27 08:50 UTC
